language: node_js

node_js:
- "node"

branches:
  only:
  - hexo

before_install:
- export TZ='Asia/Shanghai'
#- npm install -g hexo
- npm install -g hexo-cli
- npm install hexo --save
#- npm install hexo-cli --save
- npm install hexo-deployer-git --save
#- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save

install:
- npm install

# Notice: Replace 'YOUR NAME' and 'YOUR EMAIL'
before_script:
- git config --global user.name 'youlingman'
- git config --global user.email 'chenyoucyl@gmail.com'

script:
- hexo generate

after_success:
- git clone --depth=50 --branch=master https://github.com/youlingman/youlingman.github.com.git .deploy_git
- sed -i'' "s~git@github.com:youlingman/youlingman.github.com.git~https://${GITHUB_API_KEY}:x-oauth-basic@github.com/youlingman/youlingman.github.com.git~" _config.yml
- hexo deploy --silent