permalink: /:month-:day-:year/:title

auto: true
pygments: true

markdown:    rdiscount

title : youlingman's thought

author :
  name : youlingman
  github : youlingman
  twitter : youlingman

production_url : http://youlingman.github.com
