# Header
menu:
  Home: /
  Archives: /archives
  Tag: /tags
  Github: https://github.com/youlingman
rss: /atom.xml

#theme
theme: jane

# Content
excerpt_link: More...
fancybox: true

# Miscellaneous
google_analytics: UA-91857907-1
favicon: /favicon.png
